# Generated by Django 5.2.4 on 2025-07-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ['-scheduled_time']},
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participant_emails',
            field=models.TextField(help_text='Comma-separated list of participant email addresses.'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', help_text='Current status of the meeting', max_length=20),
        ),
    ]
