# Generated by Django 5.2.4 on 2025-07-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', help_text='Current status of the meeting.', max_length=20),
        ),
    ]
