# Generated by Django 5.2.4 on 2025-07-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='passcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
