# Generated by Django 5.2.4 on 2025-07-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
